"""
Django settings for wheelstreet project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p8qbzh)&k^o1^4v^evjgxbr8s8jusqz-3r-8mirm=%y7%*my90'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    

    'django_light',

    'admin_tools_stats',
    'django_nvd3',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wheelstreet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wheelstreet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata' 

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Add these lines to the settings.py file
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # or specify a custom directory


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'  # Redirect users to 'login' if not logged in
LOGIN_REDIRECT_URL = 'home'  # Redirect users to homepage after successful login

JAZZMIN_SETTINGS = {
    # Other settings...

    "site_title": "Admin Panel",
    "site_header": "WheelStreet Admin",
    "site_brand": "WheelStreet",
    "welcome_sign": "Welcome to WheelStreet",
    "copyright": "WheelStreet",
    "search_model": ["auth.User"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_models": ["auth.group", "admin_tools_stats.cached_values"],
    "order_with_respect_to": ["auth", "main"],

    "custom_links": {
        "admin_tools_stats": [{
            "name": "Bike rentals over time",
            "url": "http://127.0.0.1:8000/admin_tools_stats/analytics/?show=bikerentals",
            "icon": "fas fa-chart-line text-success fa-lg",
            "badge": "New",
            "badge_color": "badge-danger",
        },
        {
            "name": "User Graph",
            "url": "http://127.0.0.1:8000/admin_tools_stats/analytics/?show=usergraph",
            "icon": "fas fa-chart-bar text-primary fa-lg",
            "badge": "Updated",
            "badge_color": "badge-warning",
        }]
    },

    # Custom icons for apps
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.bike": "fas fa-motorcycle",
        "main.location": "fas fa-map",
        "main.rental": "fas fa-store",
    },

    # Here we will inject Chart.js and Pie/Donut Chart JavaScript
    "custom_js": """
        document.addEventListener('DOMContentLoaded', function() {
            var style = document.createElement('style');
            style.innerHTML = `
                /* Inline custom styles */
                .btn {
                    border-radius: 8px;
                    transition: all 0.3s ease;
                }
                .btn:hover {
                    background-color: #007bff;
                    color: #fff;
                }
                body {
                    font-family: 'Roboto', sans-serif;
                    background-color: #f4f6f9;
                }
                .sidebar .nav-link {
                    font-weight: bold;
                }
                .sidebar .nav-link:hover {
                    background-color: #343a40;
                    color: #ffffff;
                }
            `;
            document.head.appendChild(style);

            // Add Chart.js library from CDN
            var chartJsScript = document.createElement('script');
            chartJsScript.src = 'https://cdn.jsdelivr.net/npm/chart.js';
            document.head.appendChild(chartJsScript);

            // Wait for Chart.js to load before rendering charts
            chartJsScript.onload = function() {
                // Create a Pie Chart
                var ctxPie = document.getElementById('pieChart').getContext('2d');
                var pieChart = new Chart(ctxPie, {
                    type: 'pie',
                    data: {
                        labels: ['Red', 'Blue', 'Yellow'],
                        datasets: [{
                            label: '# of Votes',
                            data: [12, 19, 3],
                            backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56'],
                        }]
                    },
                    options: {
                        responsive: true
                    }
                });

                // Create a Donut Chart
                var ctxDonut = document.getElementById('donutChart').getContext('2d');
                var donutChart = new Chart(ctxDonut, {
                    type: 'doughnut',
                    data: {
                        labels: ['Direct', 'Referral', 'Organic'],
                        datasets: [{
                            label: '# of Users',
                            data: [300, 50, 100],
                            backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56'],
                        }]
                    },
                    options: {
                        responsive: true
                    }
                });
            };

            // Insert the chart containers into the page
            var contentArea = document.querySelector('.dashboard-header'); // Or any specific place you'd like to inject the chart
            if (contentArea) {
                contentArea.innerHTML += `
                    <div style="display: flex; justify-content: space-around; margin-top: 30px;">
                        <div>
                            <h3>Pie Chart</h3>
                            <canvas id="pieChart" width="400" height="400"></canvas>
                        </div>
                        <div>
                            <h3>Donut Chart</h3>
                            <canvas id="donutChart" width="400" height="400"></canvas>
                        </div>
                    </div>
                `;
            }
        });
    """,

    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
}
